INSERT INTO "Team" ("league", "externalId", "name", "abbreviation", "city", "conference", "division", "createdAt", "updatedAt") VALUES
('NBA', '1610612737', 'Atlanta Hawks', 'ATL', 'Atlanta', 'Eastern', 'Southeast', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612738', 'Boston Celtics', 'BOS', 'Boston', 'Eastern', 'Atlantic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612751', 'Brooklyn Nets', 'BKN', 'Brooklyn', 'Eastern', 'Atlantic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612766', 'Charlotte Hornets', 'CHA', 'Charlotte', 'Eastern', 'Southeast', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612741', 'Chicago Bulls', 'CHI', 'Chicago', 'Eastern', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612739', 'Cleveland Cavaliers', 'CLE', 'Cleveland', 'Eastern', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612742', 'Dallas Mavericks', 'DAL', 'Dallas', 'Western', 'Southwest', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612743', 'Denver Nuggets', 'DEN', 'Denver', 'Western', 'Northwest', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612765', 'Detroit Pistons', 'DET', 'Detroit', 'Eastern', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612744', 'Golden State Warriors', 'GSW', 'Golden State', 'Western', 'Pacific', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612745', 'Houston Rockets', 'HOU', 'Houston', 'Western', 'Southwest', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612754', 'Indiana Pacers', 'IND', 'Indiana', 'Eastern', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612746', 'LA Clippers', 'LAC', 'LA', 'Western', 'Pacific', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612747', 'Los Angeles Lakers', 'LAL', 'Los Angeles', 'Western', 'Pacific', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612763', 'Memphis Grizzlies', 'MEM', 'Memphis', 'Western', 'Southwest', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612748', 'Miami Heat', 'MIA', 'Miami', 'Eastern', 'Southeast', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612749', 'Milwaukee Bucks', 'MIL', 'Milwaukee', 'Eastern', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612750', 'Minnesota Timberwolves', 'MIN', 'Minnesota', 'Western', 'Northwest', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612740', 'New Orleans Pelicans', 'NOP', 'New Orleans', 'Western', 'Southwest', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612752', 'New York Knicks', 'NYK', 'New York', 'Eastern', 'Atlantic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612760', 'Oklahoma City Thunder', 'OKC', 'Oklahoma City', 'Western', 'Northwest', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612753', 'Orlando Magic', 'ORL', 'Orlando', 'Eastern', 'Southeast', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612755', 'Philadelphia 76ers', 'PHI', 'Philadelphia', 'Eastern', 'Atlantic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612756', 'Phoenix Suns', 'PHX', 'Phoenix', 'Western', 'Pacific', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612757', 'Portland Trail Blazers', 'POR', 'Portland', 'Western', 'Northwest', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612758', 'Sacramento Kings', 'SAC', 'Sacramento', 'Western', 'Pacific', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612759', 'San Antonio Spurs', 'SAS', 'San Antonio', 'Western', 'Southwest', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612761', 'Toronto Raptors', 'TOR', 'Toronto', 'Eastern', 'Atlantic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612762', 'Utah Jazz', 'UTA', 'Utah', 'Western', 'Northwest', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('NBA', '1610612764', 'Washington Wizards', 'WAS', 'Washington', 'Eastern', 'Southeast', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '109', 'Arizona Diamondbacks', 'ARI', 'Arizona', 'National', 'West', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '144', 'Atlanta Braves', 'ATL', 'Atlanta', 'National', 'East', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '110', 'Baltimore Orioles', 'BAL', 'Baltimore', 'American', 'East', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '111', 'Boston Red Sox', 'BOS', 'Boston', 'American', 'East', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '112', 'Chicago Cubs', 'CHC', 'Chicago', 'National', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '145', 'Chicago White Sox', 'CWS', 'Chicago', 'American', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '113', 'Cincinnati Reds', 'CIN', 'Cincinnati', 'National', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '114', 'Cleveland Guardians', 'CLE', 'Cleveland', 'American', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '115', 'Colorado Rockies', 'COL', 'Colorado', 'National', 'West', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '116', 'Detroit Tigers', 'DET', 'Detroit', 'American', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '117', 'Houston Astros', 'HOU', 'Houston', 'American', 'West', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '118', 'Kansas City Royals', 'KC', 'Kansas City', 'American', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '108', 'Los Angeles Angels', 'LAA', 'Los Angeles', 'American', 'West', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '119', 'Los Angeles Dodgers', 'LAD', 'Los Angeles', 'National', 'West', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '146', 'Miami Marlins', 'MIA', 'Miami', 'National', 'East', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '158', 'Milwaukee Brewers', 'MIL', 'Milwaukee', 'National', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '142', 'Minnesota Twins', 'MIN', 'Minnesota', 'American', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '121', 'New York Mets', 'NYM', 'New York', 'National', 'East', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '147', 'New York Yankees', 'NYY', 'New York', 'American', 'East', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '133', 'Athletics', 'ATH', 'Athletics', 'American', 'West', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '143', 'Philadelphia Phillies', 'PHI', 'Philadelphia', 'National', 'East', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '134', 'Pittsburgh Pirates', 'PIT', 'Pittsburgh', 'National', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '135', 'San Diego Padres', 'SD', 'San Diego', 'National', 'West', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '137', 'San Francisco Giants', 'SF', 'San Francisco', 'National', 'West', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '136', 'Seattle Mariners', 'SEA', 'Seattle', 'American', 'West', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '138', 'St. Louis Cardinals', 'STL', 'St. Louis', 'National', 'Central', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '139', 'Tampa Bay Rays', 'TB', 'Tampa Bay', 'American', 'East', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '140', 'Texas Rangers', 'TEX', 'Texas', 'American', 'West', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '141', 'Toronto Blue Jays', 'TOR', 'Toronto', 'American', 'East', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', '120', 'Washington Nationals', 'WSH', 'Washington', 'National', 'East', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("league", "externalId") DO UPDATE SET
  "name" = EXCLUDED."name",
  "abbreviation" = EXCLUDED."abbreviation",
  "city" = EXCLUDED."city",
  "conference" = EXCLUDED."conference",
  "division" = EXCLUDED."division",
  "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "SourceSync" ("league", "source", "entity", "status", "message", "fetchedAt", "createdAt", "updatedAt") VALUES
('NBA', 'NBA.com Stats API', 'teams', 'SEEDED_TEAMS_ONLY', '已匯入真實球隊清單，尚未同步比賽資料', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MLB', 'MLB StatsAPI', 'teams', 'SEEDED_TEAMS_ONLY', '已匯入真實球隊清單，尚未同步比賽資料', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("league", "source", "entity") DO UPDATE SET
  "status" = EXCLUDED."status",
  "message" = EXCLUDED."message",
  "fetchedAt" = CURRENT_TIMESTAMP,
  "updatedAt" = CURRENT_TIMESTAMP;
